#!/bin/bash --debugger

GREEN='\e[0;32m'
WHITE='\e[0;37m'
UNSET='\e[0m'
RED='\e[0;31m'


for script in `ls *.spec`
do
	cd `echo $script | sed -e 's/\.spec//'`
	echo -en "\n\n${WHITE}===> ${RED}[${GREEN} $script ${RED}]${UNSET}\n"
	cp ../$script .
	eval "./$script"
	rm ./$script
	cd ..
done
