return {
  { "leafoftree/vim-svelte-plugin" },
  { "pangloss/vim-javascript" },
  { "tpope/vim-rails" },
  { "scrooloose/nerdtree" },
  { "scrooloose/nerdcommenter" },
  { "tpope/vim-fugitive" },
  { "tpope/vim-abolish" },
  { "Raimondi/delimitMate" },
  { "tpope/vim-endwise" },
  { "tpope/vim-surround" },
  { "mattn/gist-vim" },
  { "tpope/vim-rake" },
  { "vim-ruby/vim-ruby" },
  { "tpope/vim-haml" },
  { "juvenn/mustache.vim" },
  { "tpope/vim-markdown" },
  { "tpope/vim-repeat" },
  { "tpope/vim-git" },
  { "bkad/CamelCaseMotion" },
  { "vim-scripts/YankRing.vim" },
  { "vim-scripts/bufexplorer.zip" },
  { "AndrewRadev/splitjoin.vim" },
  { "mileszs/ack.vim" },
  { "tpope/vim-bundler" },
  { "tpope/vim-rvm" },
  { "mattn/webapi-vim" },
  { "tpope/vim-rsi" },
  { "tpope/vim-dispatch" },
  { "bogado/file-line" },
  { "tpope/vim-projectionist" },
  { "szw/vim-tags" },
  { "henrik/vim-indexed-search" },
  { "jiangmiao/auto-pairs" },
  { "tpope/vim-dadbod" },
  { "mxw/vim-jsx" },
  { "peitalin/vim-jsx-typescript" },
  { "leafgarland/typescript-vim" },
  { "janko/vim-test" },
  {
    "dense-analysis/ale",
    -- ALE's LSP diagnostic handlers don't guard against nil result (valid per
    -- LSP spec when server returns null). Patch until fixed upstream.
    build = "sed -i '' 's/if err == nil then/if err == nil and result ~= nil then/g' lua/ale/lsp.lua",
  },
  { "Shougo/neoyank.vim" },
  { "ruanyl/vim-gh-line" },
  { "tomlion/vim-solidity" },
  { "junegunn/fzf" },
  { "junegunn/fzf.vim" },
  { "itchyny/lightline.vim" },
  {
    "folke/flash.nvim",
    event = "VeryLazy",
    ---@type Flash.Config
    opts = {},
    keys = {
      { "zk", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
      { "Zk", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
      { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
      { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
      { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
    },
  },
  { 
    "bogdan/vim-inkpot-refilled",
    lazy = false,
    priority = 1000,
    config = function()
      vim.cmd.colorscheme("inkpot")
    end,
  },   
}
