return {
  { "pangloss/vim-javascript" },
  { "tpope/vim-rails" },
  { "scrooloose/nerdtree" },
  { "scrooloose/nerdcommenter" },
  { "tpope/vim-fugitive" },
  { "tpope/vim-abolish" },
  { "Raimondi/delimitMate" },
  { "tpope/vim-endwise" },
  { "tpope/vim-surround" },
  { "mattn/gist-vim" },
  { "tpope/vim-rake" },
  { "vim-ruby/vim-ruby" },
  { "tpope/vim-haml" },
  { "juvenn/mustache.vim" },
  { "tpope/vim-markdown" },
  { "tpope/vim-repeat" },
  { "tpope/vim-git" },
  { "bkad/CamelCaseMotion" },
  { "vim-scripts/YankRing.vim" },
  { "vim-scripts/bufexplorer.zip" },
  { "AndrewRadev/splitjoin.vim" },
  { "mileszs/ack.vim" },
  { "tpope/vim-bundler" },
  { "tpope/vim-rvm" },
  { "mattn/webapi-vim" },
  { "tpope/vim-rsi" },
  { "SirVer/ultisnips" },
  { "tpope/vim-dispatch" },
  { "bogado/file-line" },
  { "tpope/vim-projectionist" },
  { "szw/vim-tags" },
  { "henrik/vim-indexed-search" },
  { "jiangmiao/auto-pairs" },
  { "tpope/vim-dadbod" },
  { "mxw/vim-jsx" },
  { "peitalin/vim-jsx-typescript" },
  { "leafgarland/typescript-vim" },
  { "janko/vim-test" },
  { "w0rp/ale" },
  { "Shougo/neoyank.vim" },
  { "ruanyl/vim-gh-line" },
  { "tomlion/vim-solidity" },
  { "junegunn/fzf" },
  { "junegunn/fzf.vim" },
  { "itchyny/lightline.vim" },
  { 
    "bogdan/vim-inkpot-refilled",
    lazy = false,
    priority = 1000,
    config = function()
      vim.cmd.colorscheme("inkpot")
    end,
  },
}

